name: Venome
services:

  catalog-api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: ./src
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile
  # Sql Server Container
  catalog-db:
    image: mcr.microsoft.com/mssql/server:2022-latest

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin@12345Strong"

    ports:
      - "1433:1433"

    volumes:
      - catalog-db-data:/var/opt/mssql

volumes:
  catalog-db-data: